### ISSUE TITLE
Join the team plz

### ISSUE THREAD

**Issue by IHaoT** [datawhalechina/fun-transformer#2]
Hi，Could you add me to the WeChat group? The WeChat group is already full.

**Comment by Spr1ng7** [comment]
You can send your wechat account to me via email. My email address is ***@***.***

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/05/2024 15:10 |
| To | datawhalechina/fun-transformer ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [datawhalechina/fun-transformer] Join the team plz (Issue #2) |

Hi，Could you add me to the WeChat group? The WeChat group is already full.

**Comment by IHaoT** [comment]
你好，我的微信是ZH11550,可以拉我进群吗 &nbsp;


Grain&nbsp;Buds
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月5日(星期四) 下午3:11
收件人: "datawhalechina/fun-transformer";
抄送: "Author";
主题: Re: [datawhalechina/fun-transformer] Join the team plz (Issue #2)





 Please give me your wechat account, I will add you as a friend, then I can pull you into the group
 
 ---- Replied Message ----
 | From | ***@***.***&gt; |
 | Date | 12/05/2024 15:10 |
 | To | datawhalechina/fun-transformer ***@***.***&gt; |
 | Cc | Subscribed ***@***.***&gt; |
 | Subject | [datawhalechina/fun-transformer] Join the team plz (Issue #2) |
 
 Hi，Could you add me to the WeChat group? The WeChat group is already full.
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
&mdash;

**Comment by Spr1ng7** [comment]
好友申请给你发过去了，通过一下
