### ISSUE TITLE
md显示

### ISSUE THREAD

**Issue by Pinery-lee** [datawhalechina/fun-transformer#3]
第一章introduction，原来的<bos>和<eos>无法正确显示：
- <bos>：Begin Of Sequence（BOS）
- <eos>：End Of Sequence（EOS）

改为
- \<bos\>：Begin Of Sequence（BOS）
- \<eos\>：End Of Sequence（EOS）

**Comment by Spr1ng7** [comment]
好的已修改，感谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月05日 17:38 |
| 收件人 | datawhalechina/fun-transformer ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [datawhalechina/fun-transformer] md显示 (Issue #3) |

第一章introduction，原来的和无法正确显示：

：Begin Of Sequence（BOS）
：End Of Sequence（EOS）

改为

<bos>：Begin Of Sequence（BOS）
<eos>：End Of Sequence（EOS）
