### ISSUE TITLE
fun-transformer/docs/chapter3/Encoder.md中 公式修改 

### ISSUE THREAD

**Issue by RiverTre** [datawhalechina/fun-transformer#6]
fun-transformer/docs/chapter3/Encoder.md中，{体现在公式上就是Attention(X,X,X)，X是输入序列}

这个公式是不是不对呀？Attention的输入是QKV，这里讲自注意力，应该是Attention(Q_x, K_x, V_x), 对同一个输入X，分别进行三种独立的线性变换后的结果值，输入Attention。

**Comment by Spr1ng7** [comment]
谢谢指出，在这里是想突出对同一个输入序列进行线性变换，可能有点没表达清楚。我修改了一下，看看效果如何～

**Comment by RiverTre** [comment]
> 谢谢指出，在这里是想突出对同一个输入序列进行线性变换，可能有点没表达清楚。我修改了一下，看看效果如何～

Thanks! 很清晰了 Quite Clear
