### ISSUE TITLE
Class名称纠正 fun-transformer/docs/chapter3/Cross-Attention.ipynb

### ISSUE THREAD

**Issue by RiverTre** [datawhalechina/fun-transformer#7]
fun-transformer/docs/chapter3/Cross-Attention.ipynb中，

class名写错了吧？这里没有看到multihead操作耶，类名应该是CrossAttention吧？

**Comment by Spr1ng7** [comment]
猜你想问Cross-Attention.ipynb中没有用到CrossAttention。这里是我代码粘贴错了，感谢指出。作者目前在赶ddl，今天之内修改并提醒你，谢谢啦～

**Comment by Spr1ng7** [comment]
CrossAttention代码已上传，文件名也是CrossAttention。Cross-Attention.ipynb将于今晚删除，谢谢提醒～
